log_level: info

raindrop_token:
raindrop_source_collection_id:
raindrop_target_collection_id:

openai_api_key: sk-....

prompt: |
  Can you provide a comprehensive summary of the given text? The summary should cover all the key points and main ideas presented in the original text, while also condensing the information into a concise and easy-to-understand format. Please ensure that the summary includes relevant details and examples that support the main ideas, while avoiding any unnecessary information or repetition. The length of the summary should be appropriate for the length and complexity of the original text, providing a clear and accurate overview without omitting any important information. The summary must be written in polish language and Markdown format. At the end of the summary, please provide a list of keywords that best describe the content of the text.

  Output format:
  # Podsumowanie
  <summary>

  Słowa kluczowe: <keywords>
