---
name: Build and Push Docker Image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏧 Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 📝 Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: thevops/youtube-summarizer
          tags: |
            type=sha
            type=semver,pattern={{version}}

      - name: 📦 Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
